site_name: Visualising Satellite Networks
repo_url: https://github.com/joshua99911/VisualisingSatelliteNetworks
site_url: https://joshua99911.github.io/VisualisingSatelliteNetworks
repo_name: GitHub
nav:
  - Home: index.md
  - About: about.md
  - Emulation: 
    - Emulation/purpose.md
    - Emulation/torus_topo.md
    - Emulation/simclient.md
    - Emulation/simapi.md
    - Emulation/run_mn.md
    - Emulation/pmonitor.md
    - Emulation/geosimsat.md
    - Emulation/frr_topo.md
    - Emulation/frr_config_topo.md
    - Emulation/driver.md

  - Simulation: 
    - Simulation/simulation.md
  - Setup: Setup.md
  - DocStrings: DocStrings.md
theme:
  name: mkdocs
plugins:
  - search
  - mkdocstrings:
      default_handler: python
